services:
  # Streamlit Web Service
  - type: web
    name: job-market-dashboard
    env: docker
    plan: free
    branch: main
    repo: https://github.com/PARTHUPMAN/job-market-intelligence
    envVars:
      - key: DATABASE_URL
        sync: false # Set this manually in Render Dashboard once you get it from Neon!
